[General]
no-cmake-calls=true
; importPaths="/home/kdab/Qt6.8/6.8.0/gcc_64/qml"
importPaths="/home/kdab/Documents/projects/3371-Rust-RnD/cxx-qt/build/"
buildDir="/home/kdab/Documents/projects/3371-Rust-RnD/cxx-qt/build/
